name: Manual Go Build
on:
  workflow_dispatch:
    inputs:
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_url: ${{ steps.upload_step.outputs.artifact_url }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.1'
    - name: Build
      run: CGO_ENABLED=0 go build -v -trimpath -ldflags="-s -w" -o gopp .
    - name: Upload artifact to 0x0.st
      id: upload_step
      run: |
        # 压缩二进制文件
        echo "Compressing gopp binary..."
        gzip -c ./gopp > gopp.gz
        
        # 上传压缩后的文件到 0x0.st 并捕获 URL
        echo "Uploading gopp.gz to 0x0.st..."
        UPLOAD_URL=$(curl -F "file=@gopp.gz" https://0x0.st/)
        
        # 输出上传 URL 到日志
        echo "Uploaded to: $UPLOAD_URL"
        
        # 设置步骤输出变量
        echo "artifact_url=$UPLOAD_URL" >> $GITHUB_OUTPUT
        
        # 添加到工作流摘要
        echo "### 构建产物下载链接 :rocket:" >> $GITHUB_STEP_SUMMARY
        echo "构建产物下载链接: $UPLOAD_URL" >> $GITHUB_STEP_SUMMARY